- name: Add user Django
  user:
    name: "{{ username }}"
    shell: /bin/bash
    group: users
    update_password: on_create
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  become: yes
