---
- name : Adding group users
  ansible.builtin.group:
    name:  users
    state: present

- name: Adding user ...
  user:
    name: "{{ username }}"
    shell: /bin/bash
    update_password: on_create
    generate_ssh_key: yes
    ssh_key_bits: 2048
    groups: users
    append: true
    ssh_key_file: .ssh/id_rsa
  become: yes

