---
- name: Info to add pubkey on github
  debug:
    msg: Adicionar chave privada na conta github

- name: Adding repo vimrc
  git:
    repo: 'git@github.com:mateuscomh/CONFIGS.git' 
    dest: /scripts/gitclones/
    force: yes
  become: true
  become_user: '{{ username }}'

