---
- name: Making dir .urxvt
  ansible.builtin.file:
    path: '/home/{{ username }}/.urxvt'
    state: directory
  become: true
  become_user: '{{ username }}'

- name: Making subdir .urxvt
  ansible.builtin.file:
    path: '/home/{{ username }}/.urxvt/{{ item.path }}'
    state: directory 
  with_filetree:
    - ".urxvt/"
  when: item.state == 'directory'
  loop_control:
    label: "{{ item.path }}"
  become: true
  become_user: '{{ username }}'

- name: Copying urxvt folder files
  copy:
    src: '{{ item.src }}'
    dest: '/home/{{ username }}/.urxvt/{{ item.path }}'
  with_filetree: 
    - ".urxvt/"
  when: item.state == 'file'
  loop_control:
    label: "{{ item.path }}"
  become: true
  become_user: '{{ username }}'

- name: Copying urxt config files
  copy:
    src: "{{ item }}"
    dest: '/home/{{ username }}/'
  loop:
    - '.Xdefaults'
    - '.Xresources'
  become: true
  become_user: '{{ username }}'
