---
- name: Add repo vimrc
  ansible.builtin.git:
    repo: https://github.com/mateuscomh/vimrc.git
    dest: /scripts/configs/
    force: yes
  become: yes

- name : Change file owner vimrc
  ansible.builtin.file:
    path: '/scripts/configs/{{ item }}'
    owner: "{{ username }}"
    group: users
    mode: '0766'
  loop:
    - pluginstall
    - vimrc
  become: yes

- name: Making symlink .vimrc
  ansible.builtin.file:
    src: '/scripts/configs/vimrc'
    path: '/home/{{ username }}/.vimrc'
    force: yes
  become: true
  become_user: '{{ username }}'

- name: Folder Pluginstall
  ansible.builtin.file:
    path: '/home/{{ username }}/.vim/autoload'
    state: directory
    recurse: yes
    owner: '{{ username }}'
  become: yes
  
- name: Making symlink plugvim
  ansible.builtin.file:
    src: /scripts/configs/pluginstall
    dest: '/home/{{ username }}/.vim/autoload/plug.vim'
    state: link
    owner: '{{ username }}'
  become: true
  become_user: '{{ username }}'

- name: Installing Plugvim
  command: "vim +PlugInstall +qall"
  become: true
  become_user: '{{ username }}'
