---
- name : Adding group users
  ansible.builtin.group:
    name:  users
    state: present
  become: yes

- name: Add user
  user:
    name: "{{ username }}"
    shell: /bin/bash
    update_password: on_create
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    groups: users
    append: yes
  become: yes

- name: Add users in a sudores
  user:
    name: "{{ username }}"
    groups: sudo
    append: yes
  with_items: "{{ username }}"
  become: yes

- name: Print rsa_key.pub
  shell: cat "/home/{{ username }}/.ssh/id_rsa.pub"
  register: command_output

- debug:
    var: command_output.stdout_lines

- name: Info to add pubkey on github
  debug:
    msg: Adicionar chave privada na conta github
