---
- name : Adding group users
  ansible.builtin.group:
    name:  users
    state: present

- name: Add user
  user:
    name: "{{ username }}"
    shell: /bin/bash
    update_password: on_create
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    groups: users
    append: true
  become: true
  tags: add_user

- name: Print rsa_key.pub
  shell: cat "/home/{{ username }}/.ssh/id_rsa.pub"
  register: command_output
  become: true
  tags: add_user

- debug:
    var: command_output.stdout_lines
  tags: add_user
